/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWhoamiRouteImport } from './routes/api/whoami'
import { Route as ApiUploadFinalizeRouteImport } from './routes/api/upload-finalize'
import { Route as ApiUploadChunkRouteImport } from './routes/api/upload-chunk'
import { Route as ApiUnlockRouteImport } from './routes/api/unlock'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiLockRouteImport } from './routes/api/lock'
import { Route as ApiFoldersRouteImport } from './routes/api/folders'
import { Route as ApiFilesRouteImport } from './routes/api/files'
import { Route as ApiFoldersIdRouteImport } from './routes/api/folders.$id'
import { Route as ApiFilesDownloadZipRouteImport } from './routes/api/files.download-zip'
import { Route as ApiFilesIdRouteImport } from './routes/api/files.$id'
import { Route as ApiFilesIdThumbRouteImport } from './routes/api/files.$id.thumb'
import { Route as ApiFilesIdStreamRouteImport } from './routes/api/files.$id.stream'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhoamiRoute = ApiWhoamiRouteImport.update({
  id: '/api/whoami',
  path: '/api/whoami',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadFinalizeRoute = ApiUploadFinalizeRouteImport.update({
  id: '/api/upload-finalize',
  path: '/api/upload-finalize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadChunkRoute = ApiUploadChunkRouteImport.update({
  id: '/api/upload-chunk',
  path: '/api/upload-chunk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnlockRoute = ApiUnlockRouteImport.update({
  id: '/api/unlock',
  path: '/api/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLockRoute = ApiLockRouteImport.update({
  id: '/api/lock',
  path: '/api/lock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFoldersRoute = ApiFoldersRouteImport.update({
  id: '/api/folders',
  path: '/api/folders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFoldersIdRoute = ApiFoldersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiFoldersRoute,
} as any)
const ApiFilesDownloadZipRoute = ApiFilesDownloadZipRouteImport.update({
  id: '/download-zip',
  path: '/download-zip',
  getParentRoute: () => ApiFilesRoute,
} as any)
const ApiFilesIdRoute = ApiFilesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiFilesRoute,
} as any)
const ApiFilesIdThumbRoute = ApiFilesIdThumbRouteImport.update({
  id: '/thumb',
  path: '/thumb',
  getParentRoute: () => ApiFilesIdRoute,
} as any)
const ApiFilesIdStreamRoute = ApiFilesIdStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiFilesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/unlock': typeof UnlockRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/folders': typeof ApiFoldersRouteWithChildren
  '/api/lock': typeof ApiLockRoute
  '/api/status': typeof ApiStatusRoute
  '/api/unlock': typeof ApiUnlockRoute
  '/api/upload-chunk': typeof ApiUploadChunkRoute
  '/api/upload-finalize': typeof ApiUploadFinalizeRoute
  '/api/whoami': typeof ApiWhoamiRoute
  '/api/files/$id': typeof ApiFilesIdRouteWithChildren
  '/api/files/download-zip': typeof ApiFilesDownloadZipRoute
  '/api/folders/$id': typeof ApiFoldersIdRoute
  '/api/files/$id/stream': typeof ApiFilesIdStreamRoute
  '/api/files/$id/thumb': typeof ApiFilesIdThumbRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/unlock': typeof UnlockRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/folders': typeof ApiFoldersRouteWithChildren
  '/api/lock': typeof ApiLockRoute
  '/api/status': typeof ApiStatusRoute
  '/api/unlock': typeof ApiUnlockRoute
  '/api/upload-chunk': typeof ApiUploadChunkRoute
  '/api/upload-finalize': typeof ApiUploadFinalizeRoute
  '/api/whoami': typeof ApiWhoamiRoute
  '/api/files/$id': typeof ApiFilesIdRouteWithChildren
  '/api/files/download-zip': typeof ApiFilesDownloadZipRoute
  '/api/folders/$id': typeof ApiFoldersIdRoute
  '/api/files/$id/stream': typeof ApiFilesIdStreamRoute
  '/api/files/$id/thumb': typeof ApiFilesIdThumbRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/unlock': typeof UnlockRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/folders': typeof ApiFoldersRouteWithChildren
  '/api/lock': typeof ApiLockRoute
  '/api/status': typeof ApiStatusRoute
  '/api/unlock': typeof ApiUnlockRoute
  '/api/upload-chunk': typeof ApiUploadChunkRoute
  '/api/upload-finalize': typeof ApiUploadFinalizeRoute
  '/api/whoami': typeof ApiWhoamiRoute
  '/api/files/$id': typeof ApiFilesIdRouteWithChildren
  '/api/files/download-zip': typeof ApiFilesDownloadZipRoute
  '/api/folders/$id': typeof ApiFoldersIdRoute
  '/api/files/$id/stream': typeof ApiFilesIdStreamRoute
  '/api/files/$id/thumb': typeof ApiFilesIdThumbRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/unlock'
    | '/api/files'
    | '/api/folders'
    | '/api/lock'
    | '/api/status'
    | '/api/unlock'
    | '/api/upload-chunk'
    | '/api/upload-finalize'
    | '/api/whoami'
    | '/api/files/$id'
    | '/api/files/download-zip'
    | '/api/folders/$id'
    | '/api/files/$id/stream'
    | '/api/files/$id/thumb'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/unlock'
    | '/api/files'
    | '/api/folders'
    | '/api/lock'
    | '/api/status'
    | '/api/unlock'
    | '/api/upload-chunk'
    | '/api/upload-finalize'
    | '/api/whoami'
    | '/api/files/$id'
    | '/api/files/download-zip'
    | '/api/folders/$id'
    | '/api/files/$id/stream'
    | '/api/files/$id/thumb'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/unlock'
    | '/api/files'
    | '/api/folders'
    | '/api/lock'
    | '/api/status'
    | '/api/unlock'
    | '/api/upload-chunk'
    | '/api/upload-finalize'
    | '/api/whoami'
    | '/api/files/$id'
    | '/api/files/download-zip'
    | '/api/folders/$id'
    | '/api/files/$id/stream'
    | '/api/files/$id/thumb'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  UnlockRoute: typeof UnlockRoute
  ApiFilesRoute: typeof ApiFilesRouteWithChildren
  ApiFoldersRoute: typeof ApiFoldersRouteWithChildren
  ApiLockRoute: typeof ApiLockRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiUnlockRoute: typeof ApiUnlockRoute
  ApiUploadChunkRoute: typeof ApiUploadChunkRoute
  ApiUploadFinalizeRoute: typeof ApiUploadFinalizeRoute
  ApiWhoamiRoute: typeof ApiWhoamiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whoami': {
      id: '/api/whoami'
      path: '/api/whoami'
      fullPath: '/api/whoami'
      preLoaderRoute: typeof ApiWhoamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-finalize': {
      id: '/api/upload-finalize'
      path: '/api/upload-finalize'
      fullPath: '/api/upload-finalize'
      preLoaderRoute: typeof ApiUploadFinalizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-chunk': {
      id: '/api/upload-chunk'
      path: '/api/upload-chunk'
      fullPath: '/api/upload-chunk'
      preLoaderRoute: typeof ApiUploadChunkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unlock': {
      id: '/api/unlock'
      path: '/api/unlock'
      fullPath: '/api/unlock'
      preLoaderRoute: typeof ApiUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lock': {
      id: '/api/lock'
      path: '/api/lock'
      fullPath: '/api/lock'
      preLoaderRoute: typeof ApiLockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/folders': {
      id: '/api/folders'
      path: '/api/folders'
      fullPath: '/api/folders'
      preLoaderRoute: typeof ApiFoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/folders/$id': {
      id: '/api/folders/$id'
      path: '/$id'
      fullPath: '/api/folders/$id'
      preLoaderRoute: typeof ApiFoldersIdRouteImport
      parentRoute: typeof ApiFoldersRoute
    }
    '/api/files/download-zip': {
      id: '/api/files/download-zip'
      path: '/download-zip'
      fullPath: '/api/files/download-zip'
      preLoaderRoute: typeof ApiFilesDownloadZipRouteImport
      parentRoute: typeof ApiFilesRoute
    }
    '/api/files/$id': {
      id: '/api/files/$id'
      path: '/$id'
      fullPath: '/api/files/$id'
      preLoaderRoute: typeof ApiFilesIdRouteImport
      parentRoute: typeof ApiFilesRoute
    }
    '/api/files/$id/thumb': {
      id: '/api/files/$id/thumb'
      path: '/thumb'
      fullPath: '/api/files/$id/thumb'
      preLoaderRoute: typeof ApiFilesIdThumbRouteImport
      parentRoute: typeof ApiFilesIdRoute
    }
    '/api/files/$id/stream': {
      id: '/api/files/$id/stream'
      path: '/stream'
      fullPath: '/api/files/$id/stream'
      preLoaderRoute: typeof ApiFilesIdStreamRouteImport
      parentRoute: typeof ApiFilesIdRoute
    }
  }
}

interface ApiFilesIdRouteChildren {
  ApiFilesIdStreamRoute: typeof ApiFilesIdStreamRoute
  ApiFilesIdThumbRoute: typeof ApiFilesIdThumbRoute
}

const ApiFilesIdRouteChildren: ApiFilesIdRouteChildren = {
  ApiFilesIdStreamRoute: ApiFilesIdStreamRoute,
  ApiFilesIdThumbRoute: ApiFilesIdThumbRoute,
}

const ApiFilesIdRouteWithChildren = ApiFilesIdRoute._addFileChildren(
  ApiFilesIdRouteChildren,
)

interface ApiFilesRouteChildren {
  ApiFilesIdRoute: typeof ApiFilesIdRouteWithChildren
  ApiFilesDownloadZipRoute: typeof ApiFilesDownloadZipRoute
}

const ApiFilesRouteChildren: ApiFilesRouteChildren = {
  ApiFilesIdRoute: ApiFilesIdRouteWithChildren,
  ApiFilesDownloadZipRoute: ApiFilesDownloadZipRoute,
}

const ApiFilesRouteWithChildren = ApiFilesRoute._addFileChildren(
  ApiFilesRouteChildren,
)

interface ApiFoldersRouteChildren {
  ApiFoldersIdRoute: typeof ApiFoldersIdRoute
}

const ApiFoldersRouteChildren: ApiFoldersRouteChildren = {
  ApiFoldersIdRoute: ApiFoldersIdRoute,
}

const ApiFoldersRouteWithChildren = ApiFoldersRoute._addFileChildren(
  ApiFoldersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  UnlockRoute: UnlockRoute,
  ApiFilesRoute: ApiFilesRouteWithChildren,
  ApiFoldersRoute: ApiFoldersRouteWithChildren,
  ApiLockRoute: ApiLockRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiUnlockRoute: ApiUnlockRoute,
  ApiUploadChunkRoute: ApiUploadChunkRoute,
  ApiUploadFinalizeRoute: ApiUploadFinalizeRoute,
  ApiWhoamiRoute: ApiWhoamiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
